### ISSUE TITLE
unrecognized arguments: -forwarded-allow-ips=*

### ISSUE THREAD

**Issue by thejhh** [pvarki/python-pvas-arkia11napi#8]
What can this mean? This happens in local development using dockerization at https://github.com/pvarki/tilaa.pvarki.fi/tree/feature/initial

```
pvarki-api                | usage: gunicorn [OPTIONS] [APP_MODULE]
pvarki-api                | gunicorn: error: unrecognized arguments: -forwarded-allow-ips=*
```

**Comment by thejhh** [comment]
Ah, `docker-compose pull` probably fixes this.

**Comment by thejhh** [comment]
Nope, pull did not fix it. The problem has been fixed in the Git two hours ago, but image seems to be using the old entry file still: https://github.com/pvarki/python-pvas-arkia11napi/commit/f50c923836ab3242475d7725fe6c3eb8445f7ac2

**Comment by rambo** [comment]
Check your hash, make sure you're pulling from pvarki org not the old pvarkiprojekti one

```
docker inspect pvarki/arkia11napi
[
    {
        "Id": "sha256:603181da531ae854c9e84fb4f5b030ce06dcb9d49c7b022f65ddb293072b72f7",
        "RepoTags": [
            "pvarki/arkia11napi:latest"
        ],
        "RepoDigests": [
            "pvarki/arkia11napi@sha256:3036c0cb635d3a2ef21701239f4449ac9c28eb11eb2f3ddd2cf9c2d8fa326ada"
        ],
```

suitable-raptor is running that version

**Comment by thejhh** [comment]
Thanks. That was it! :)
